FROM python:3.9

WORKDIR /app

# 
COPY ./requirements.txt /app/requirements.txt

COPY ./_wildcard.example.com+2-key.pem /app/_wildcard.example.com+2-key.pem
COPY ./_wildcard.example.com+2.pem /app/_wildcard.example.com+2.pem

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# 
COPY . /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--ssl-keyfile","/app/_wildcard.example.com+2-key.pem","--ssl-certfile","/app/_wildcard.example.com+2.pem"]