FROM python:3.9

WORKDIR /app

# 
COPY ./requirements.txt /app/requirements.txt

COPY ./face-prediction.o-r.kr+3-key.pem /app/face-prediction.o-r.kr+3-key.pem
COPY ./face-prediction.o-r.kr+3.pem /app/face-prediction.o-r.kr+3.pem

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# 
COPY . /app

CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8080", "--ssl-keyfile","/app/face-prediction.o-r.kr+3-key.pem","--ssl-certfile","/app/face-prediction.o-r.kr+3.pem"]